sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t taninaim/docker-react -f Dockerfile.dev .

scripts:
  - docker run taninaim/docker-react npm run test -- --coverage